### ISSUE TITLE
FINAL v1.0 RELEASE BURN DOWN

### ISSUE THREAD

**Issue by vbatts** [opencontainers/runtime-spec#726] opened 2017-03-15 21:53 UTC
- [x] runc merged support https://github.com/opencontainers/runc/pull/1370 ( @crosbymichael & @mrunalp )
- [x] PR for docker rebase on this newer runc (for testing coverage) https://github.com/containerd/containerd/pull/778 ( @crosbymichael )
- [x] PR for cri-o rebase on this newer runc ( @mrunalp )
- [ ] final sanity check (build consistency, terminology consistency) ( err'body )

Time frame: by the March 29nd, 2017 to open the vote for v1.0.0 (which still has a one week voting period)

**Comment by caniszczyk** [comment] 2017-03-15 23:45
I'd add box around notifying all OCI members to review the release before it's blessed, we can send out a note to all the OCI member technical contacts

**Comment by wking** [comment] 2017-03-16 00:03
On Wed, Mar 15, 2017 at 04:45:19PM -0700, Chris Aniszczyk wrote:
> I'd add box around notifying all OCI members to review the release
> before it's blessed, we can send out a note to all the OCI member
> technical contacts

I'm not entirely clear on where the discussion ended up, but at least
@RobDolinMS was arguing for voting on an rc6 next week and making that
the hopefuly-final RC before 1.0 [1] with a 30-day review window
before 1.0.  That gives Members time to look things over ahead of time
so they can suggest changes.  If we cut 1.0 without a suitable review
period, the only option open to Members who discover something they
aren't comfortable with is resignation from the OCI [2].  And
personally, I'll be pleasantly surprised if the 16 unmilestoned issues
and PRs [3] get settled by next week.

[1]: http://ircbot.wl.linuxfoundation.org/meetings/opencontainers/2017/opencontainers.2017-03-15-21.02.log.html#l-153
[2]: https://www.opencontainers.org/about/governance §8.d
[3]: https://github.com/opencontainers/runtime-spec/issues?utf8=%E2%9C%93&q=is%3Aopen%20no%3Amilestone

**Comment by caniszczyk** [comment] 2017-03-16 14:48
@vbatts re the image-spec, will there be a similar issue like this?

**Comment by vbatts** [comment] 2017-03-16 15:26
@caniszczyk good call. I'll write it up, though the reliance on implementations being on the latest isn't just like runc.

**Comment by vbatts** [comment] 2017-03-21 17:41
@crosbymichael is there pr to link for the docker rebase?

@mrunalp is there pr to link for cri-o rebase?

**Comment by wking** [comment] 2017-03-29 17:00
From today's meeting, [cri-o is waiting][1] on opencontainers/runtime-tools#349.

[1]: http://ircbot.wl.linuxfoundation.org/meetings/opencontainers/2017/opencontainers.2017-03-29-15.02.log.html#l-8

**Comment by caniszczyk** [comment] 2017-04-03 23:17
@crosbymichael is there a docker issue open for the rebase?

**Comment by vbatts** [comment] 2017-04-03 23:22
i asked today. He said there is a contributor working on it, but no PR yet.

**Comment by philips** [comment] 2017-04-04 00:35
@vbatts what is the new ETA as March 29th has passed.

**Comment by vbatts** [comment] 2017-04-04 17:57
@philips great question. The big thing was seeing green tests on docker and cri-o being rebased, which is not a hard requirement, but just a nice-to-have.

**Comment by mrunalp** [comment] 2017-04-13 17:36
We updated cri-o to latest runtime-spec/runc. https://github.com/kubernetes-incubator/cri-o/pull/447

**Comment by caniszczyk** [comment] 2017-04-17 16:29
@crosbymichael any news on the bullet item "PR for docker rebase on this newer runc (for testing coverage)"

**Comment by caniszczyk** [comment] 2017-04-25 14:34
@crosbymichael post dockercon ping. I need to start doing a lot of PR planning and member outreach for the v1.0 so would love to know how timing looks on your end, along with the rest of the @opencontainers/runtime-spec-maintainers

**Comment by crosbymichael** [comment] 2017-04-25 15:23
Thanks for the ping.  I'll take care of it this week now that we are back from dockercon and back to development.

**Comment by caniszczyk** [comment] 2017-04-25 15:36
Thanks @crosbymichael, I'll start the PR dance work that's required for getting v1.0 out the door, look forward to the dev call this week to update folks on the plan :D

**Comment by crosbymichael** [comment] 2017-04-25 15:38
Sounds good, working on it today

**Comment by caniszczyk** [comment] 2017-04-27 19:39
containerd PR is up https://github.com/containerd/containerd/pull/778

**Comment by crosbymichael** [comment] 2017-05-05 23:25
Checked off the docker rebase.  

Lets schedule some time to do a final sanity check next week?

**Comment by mrunalp** [comment] 2017-05-06 00:06
@crosbymichael Awesome :) Sure, I'll set something up for next week (Sorry couldn't do it today as I got side-tracked).

**Comment by vbatts** [comment] 2017-05-06 17:08
:+1:

**Comment by caniszczyk** [comment] 2017-05-08 22:41
very cool cc: @opencontainers/runtime-spec-maintainers for wider awareness

**Comment by tianon** [comment] 2017-05-09 06:28
Docker seems to have a TTY-related regression since the latest update (https://github.com/moby/moby/issues/33101) -- help tracking down whether that actually matters for runtime-spec would be :100:. :heart:

**Comment by tianon** [comment] 2017-05-09 06:33
(My current testing points to bare `runc` being unaffected, and this thus being a Docker-specific bug, but having more folks verify that would be appreciated since it's late and I'm not trusting my own results ATM. :fearful: :disappointed:)

**Comment by caniszczyk** [comment] 2017-05-16 16:43
@opencontainers/runtime-spec-maintainers, I'm syncing with the OCI PR team for v1.0 planning this afternoon, is there a strong feeling on calling for a vote this week or is there still more work to do?

**Comment by vbatts** [comment] 2017-05-16 17:14
for runtime-spec, this seems fine. that would mean that it and image-spec
don't release a v1.0 at the same time.

**Comment by caniszczyk** [comment] 2017-05-16 18:36
@vbatts, I'm not sure how close image-spec is to v1.0, maybe @stevvooe can comment

At the moment, all OCI PR planning is around both going around the same time, if both runtime-spec and image-spec maintainers were willing to wait to coordinate, that would be fine, otherwise I can work with the OCI PR folks to plan things differently.

I'm also generating a list of all the OCI contributors over the last couple of years to be thanked in the PR / blog post going out, I'll share that with the group before the end of this week for a sanity check

**Comment by wking** [comment] 2017-08-02 20:45
On Wed, Mar 15, 2017 at 02:53:43PM -0700, Vincent Batts wrote:
> [ ] final sanity check (build consistency, terminology consistency)

With 1.0.0 cut, we can probably check this off, close this issue, and
close the 1.0.0 milestone (via [1]).

[1]: https://github.com/opencontainers/runtime-spec/milestones

**Comment by caniszczyk** [comment] 2017-08-02 20:51
Thanks @wking :)

https://www.opencontainers.org/announcement/2017/07/19/open-container-initiative-oci-releases-v1-0-of-container-standards

**Closed by caniszczyk** 2017-08-02 20:51 UTC

**Comment by wking** [comment] 2017-08-02 20:56
On Wed, Aug 02, 2017 at 08:51:31PM +0000, Chris Aniszczyk wrote:
> Closed #726.

That leaves [1] 100% complete, but it's still listed as “open” on [2].
Can you mark it closed there?

[1]: https://github.com/opencontainers/runtime-spec/milestone/7
[2]: https://github.com/opencontainers/runtime-spec/milestones

**Comment by wking** [comment] 2017-08-09 18:17
On Wed, Aug 02, 2017 at 01:56:48PM -0700, W. Trevor King wrote:
> On Wed, Aug 02, 2017 at 08:51:31PM +0000, Chris Aniszczyk wrote:
> > Closed #726.
> 
> That leaves [1] 100% complete, but it's still listed as “open” on [2].
> Can you mark it closed there?
> 
> [1]: https://github.com/opencontainers/runtime-spec/milestone/7
> [2]: https://github.com/opencontainers/runtime-spec/milestones

The v1.0.0 milestone is still open on [2].  Can someone with write
access close it?
