### ISSUE TITLE
json: cannot unmarshal number -1 into Go value of type uint64

### ISSUE THREAD

**Issue by xiajohnnyxia** [opencontainers/runtime-spec#867] opened 2017-05-29 10:25 UTC
/runc/vendor/github.com/opencontainers/runc/libcontainer/factory_linux.go

 func (l *LinuxFactory) loadState(root, id string) (*State, error)
                  
                   json.NewDecoder(f).Decode(&state)

In this type : State.BaseState.Config.Cgroups.Resources,there are serval unit64 type field . And their json value is number.
How can i fix this error?

```
"memory": 0,
"memory_reservation": 0,
"memory_swap": 0,
"kernel_memory": 0,
"kernel_memory_tcp": 0,
"cpu_shares": 0,
"cpu_quota": 0,
"cpu_period": 0,
"cpu_rt_quota": 0,
"cpu_rt_period": 0,
"cpuset_cpus": "",
"cpuset_mems": "",
```

```
// Memory limit (in bytes)
Memory uint64 json:"memory"

// Memory reservation or soft_limit (in bytes)
MemoryReservation uint64 `json:"memory_reservation"`

// Total memory usage (memory + swap); set `-1` to enable unlimited swap
MemorySwap uint64 `json:"memory_swap"`

// Kernel memory limit (in bytes)
KernelMemory uint64 `json:"kernel_memory"`

// Kernel memory limit for TCP use (in bytes)
KernelMemoryTCP uint64 `json:"kernel_memory_tcp"`

// CPU shares (relative weight vs. other containers)
CpuShares uint64 `json:"cpu_shares"`

// CPU hardcap limit (in usecs). Allowed cpu time in a given period.
CpuQuota int64 `json:"cpu_quota"`

// CPU period to be used for hardcapping (in usecs). 0 to use system default.
CpuPeriod uint64 `json:"cpu_period"`

// How many time CPU will use in realtime scheduling (in usecs).
CpuRtRuntime int64 `json:"cpu_rt_quota"`

// CPU period to be used for realtime scheduling (in usecs).
CpuRtPeriod uint64 `json:"cpu_rt_period"`
```

**Comment by cyphar** [comment] 2017-05-29 10:56
This error is not caused by the runtime-spec, it's a runc error. It happens because you're using an incorrect version of `config.json` with `runc`. To be fair, `runc` should be far less liberal about accepting unknown spec versions, but the solution to this is to check the output of `runc --version` and see what the `spec:` line says (then make sure your `config.json` is the same version). Most tools (`oci-runtime-tool`, `umoci` and so on) all support the new version.

```
runc version 1.0.0-rc3
commit: ac50e77bbb440dcab354a328c79754e2502b79ca-dirty
spec: 1.0.0-rc5
```

**Comment by wking** [comment] 2017-05-29 15:21
> To be fair, `runc` should be far less liberal about accepting unknown spec versions...

More on this in opencontainers/runc#521.

**Comment by wking** [comment] 2017-05-31 16:47
With opencontainers/runc#1465 closed (and this not being a runtime-spec issue in the first place) I think it's safe to close this one.

**Closed** 2017-06-02 03:02 UTC
